name: fill readme

on: push

jobs:
  fill-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python script.py
    - run: |
        git config --local user.name actions-user 
        git config --local user.email "actions@github.com"
        git diff --quiet && git diff --staged --quiet || git commit -am 'update readme' && git push -f origin master